"""Compile the unchanged lion source image to portable indexed terminal artwork.

Development only: requires Pillow. Runtime uses standard-library decoding and Rich.
"""
import base64
import hashlib
from pathlib import Path
import textwrap
import zlib

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/assets/lion-realistic.png"
TARGET = ROOT / "src/hard_implementation/lion_art.py"


def main():
    with Image.open(SOURCE) as source:
        image = source.convert("RGBA")
        largest = image.resize((64, 64), Image.Resampling.LANCZOS)
        colors = largest.convert("RGB").quantize(colors=255, method=Image.Quantize.MEDIANCUT,
                                                dither=Image.Dither.NONE)
        palette = colors.getpalette()
        entries = [None] + ["#" + bytes(palette[i:i + 3]).hex() for i in range(0, 765, 3)]
        lines = ['"""Generated by scripts/build_lion_art.py; do not hand-edit."""',
                 f'SOURCE_SHA256 = "{hashlib.sha256(SOURCE.read_bytes()).hexdigest()}"',
                 "PALETTE = (None,"]
        for i in range(1, len(entries), 8):
            lines.append("    " + ", ".join(repr(c) for c in entries[i:i + 8]) + ",")
        lines += [")", "IMAGES = {"]
        for size in (36, 48, 64):
            resized = image.resize((size, size), Image.Resampling.LANCZOS)
            indexed = resized.convert("RGB").quantize(palette=colors, dither=Image.Dither.NONE)
            pixels = bytes(index + 1 if alpha >= 64 else 0 for index, alpha in
                           zip(indexed.tobytes(), resized.getchannel("A").tobytes()))
            encoded = base64.b85encode(zlib.compress(pixels, 9)).decode("ascii")
            lines.append(f"    {size}: (")
            lines.extend('        "' + part + '"' for part in textwrap.wrap(encoded, 100,
                         break_on_hyphens=False, replace_whitespace=False))
            lines.append("    ),")
        lines += ["}", ""]
    TARGET.write_bytes("\n".join(lines).encode("utf-8"))
    print("Compiled 36/48/64-column lion artwork:", TARGET)


if __name__ == "__main__":
    main()
