"""Check current release facts, commands, references, hashes and GitHub About.

--write refreshes generated documentation and payload hashes. Historical changelog/validation
evidence and the preserved original workflow are never rewritten.
"""
import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import re
import subprocess
from urllib.parse import unquote

ROOT = Path(__file__).resolve().parents[1]


def load_engine(root):
    spec = importlib.util.spec_from_file_location("consistency_installer", root / "install.py")
    engine = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(engine)
    return engine


def project_version(root=ROOT):
    text = (root / "src/hard_implementation/__init__.py").read_text(encoding="utf-8")
    match = re.search(r'^__version__\s*=\s*[\'"]([0-9]+\.[0-9]+\.[0-9]+)[\'"]', text, re.M)
    if not match:
        raise ValueError("Missing static package version")
    return match.group(1)


def facts(root=ROOT):
    engine = load_engine(root)
    metadata = json.loads((root / "project-metadata.json").read_text(encoding="utf-8"))
    if metadata["repository"] != engine.REPOSITORY:
        raise ValueError("Repository identity differs from the installer")
    if set(metadata["agent_topics"]) != set(engine.AGENTS):
        raise ValueError("Agent topics must cover the current installer registry exactly")
    topics = sorted(set(metadata["topics"]) | set(metadata["agent_topics"].values()))
    if len(topics) > 20 or any(not re.fullmatch(r"[a-z0-9][a-z0-9-]{0,49}", t) for t in topics):
        raise ValueError("Invalid GitHub topic list")
    labels = ", ".join(info["label"] for info in engine.AGENTS.values())
    description = (f"Universal implementation workflow for {labels}. "
                   f"Supports {len(metadata['supported_systems'])} spec systems, security gates, "
                   "verification and resumable execution; complete original preserved.")
    if len(description) > 350:
        raise ValueError("Generated GitHub About exceeds 350 characters")
    return {"version": project_version(root), "repository": engine.REPOSITORY,
            "description": description, "topics": topics, "agents": engine.AGENTS,
            "systems": metadata["supported_systems"]}


def command_table(data, arabic=False):
    header = "| الأداة | أمر التشغيل |" if arabic else "| Coding agent | Chat command |"
    return "\n".join([header, "|---|---|"] + [
        f"| {info['label']} | `{info['command']}` |" for info in data["agents"].values()])


def snapshot(data):
    systems = "\n".join(f"- {name}" for name in data["systems"])
    return ("# Current project facts\n\n"
            "Generated by `scripts/check_consistency.py --write`. Historical release/test\n"
            "records remain in the changelog and validation guide.\n\n"
            f"- Current release: **v{data['version']}**\n"
            f"- Coding agents: **{len(data['agents'])}**\n"
            f"- Specification systems: **{len(data['systems'])}**\n"
            "- Security: [Universal Security Gate](../skills/hard-implementation/references/security.md)\n"
            "- Original workflow: preserved byte-for-byte; [audit](PRESERVATION.md)\n\n"
            "## GitHub About\n\n" + data["description"] + "\n\n"
            "Topics: " + ", ".join(data["topics"]) + "\n\n"
            "## Native invocation\n\n" + command_table(data) + "\n\n"
            "Hermes's optional alias and host/profile limitations are in [COMMANDS.md](COMMANDS.md).\n"
            "These are installation/role bindings; end-to-end execution evidence is scoped\n"
            "in [VALIDATION.md](VALIDATION.md), not implied for every host or board.\n\n"
            "## Native systems\n\n" + systems + "\n")


def generated_updates(root, data):
    updates = {"docs/CURRENT-STATE.md": snapshot(data)}
    for name in ("README.md", "README.ar.md", "skills/hard-implementation/SKILL.md"):
        text = (root / name).read_text(encoding="utf-8")
        block = ("<!-- BEGIN GENERATED: commands -->\n" + command_table(data, name == "README.ar.md")
                 + "\n<!-- END GENERATED: commands -->")
        pattern = r"<!-- BEGIN GENERATED: commands -->[\s\S]*?<!-- END GENERATED: commands -->"
        if len(re.findall(pattern, text)) != 1:
            raise ValueError(f"Missing/duplicate command block in {name}")
        text = re.sub(pattern, lambda _: block, text)
        if name.endswith("SKILL.md"):
            text = re.sub(r'(?m)^  version: "[^"]+"$', f'  version: "{data["version"]}"', text)
        else:
            text = re.sub(r"v\d+\.\d+\.\d+", "v" + data["version"], text)
        updates[name] = text
    return updates


def repository_files(root):
    # Include all tracked and non-ignored untracked files; archives use a fallback.
    result = subprocess.run(["git", "ls-files", "--cached", "--others", "--exclude-standard"],
                            cwd=root, text=True, capture_output=True, timeout=30)
    if result.returncode == 0:
        return sorted(set(result.stdout.splitlines()))
    return sorted(p.relative_to(root).as_posix() for p in root.rglob("*") if p.is_file()
                  and not any(part in (".git", ".venv", "dist", "__pycache__") for part in p.parts))


def markdown_issues(root, names, agents):
    errors = []
    aliases = {key: [info["label"]] for key, info in agents.items()}
    aliases["vscode"] += ["VS Code", "Copilot"]
    for name in names:
        if not name.endswith(".md"):
            continue
        text = (root / name).read_text(encoding="utf-8")
        text = re.sub(r"(?m)^(```|~~~)[\s\S]*?^\1[^\n]*$", "", text)
        for target in re.findall(r"\[[^\]\n]+\]\(([^)\n]+)\)", text):
            target = target.strip()
            target = (target[1:target.find(">")] if target.startswith("<") and ">" in target
                      else re.split(r'\s+[\'"]', target, maxsplit=1)[0])
            target = target.split("#", 1)[0]
            if not target or re.match(r"[a-z]+:|/|~", target):
                continue
            path = root / Path(name).parent / unquote(target)
            if not path.exists():
                errors.append(f"Broken local reference: {name} -> {target}")
        command_column = None
        for line in text.splitlines():
            if not line.startswith("|"):
                command_column = None
                continue
            cells = [c.strip() for c in line.strip("|").split("|")]
            headers = {"Chat command", "Chat invocation", "Invocation", "أمر التشغيل", "Immediately supported invocation"}
            found = [i for i, c in enumerate(cells) if c in headers]
            if found:
                command_column = found[0]
                continue
            if command_column is None or len(cells) <= command_column:
                continue
            label = " ".join(cells[:command_column]).replace("`", "")
            for key, choices in aliases.items():
                if re.search(rf"\b{re.escape(key)}\b", label, re.I) or any(re.search(rf"\b{re.escape(a)}\b", label, re.I) for a in choices):
                    if cells[command_column].strip("`") != agents[key]["command"]:
                        errors.append(f"Stale invocation: {name}: {key} should use {agents[key]['command']}")
    return errors


def local_issues(root, data):
    errors = []
    for name, expected in generated_updates(root, data).items():
        path = root / name
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            errors.append(f"Generated facts are stale: {name}; run scripts/check_consistency.py --write")
    engine = load_engine(root)
    if engine.RELEASE != "v" + data["version"]:
        errors.append("Installer release differs from the package version")
    for name, section in (("pyproject.toml", "[project]"), ("uv.lock", 'name = "hard-implementation"')):
        text = (root / name).read_text(encoding="utf-8").split(section, 1)[-1]
        match = re.search(r'(?m)^version = "([^"]+)"', text)
        if not match or match.group(1) != data["version"]:
            errors.append(f"Stale package version: {name}")
    manifest = json.loads((root / "distribution.json").read_text(encoding="utf-8"))
    if manifest.get("version") != data["version"]:
        errors.append("Stale distribution version")
    required = "skills/hard-implementation/references/security.md"
    if required not in manifest.get("files", {}):
        errors.append("Universal Security Gate missing from the distributed payload")
    actual = {p.relative_to(root).as_posix() for folder in ("skills", "adapters")
              for p in (root / folder).rglob("*") if p.is_file()
              and "__pycache__" not in p.parts and p.suffix != ".pyc"}
    if set(manifest.get("files", {})) != actual:
        errors.append("Distribution manifest does not cover the full skill/adapter payload")
    for name, sha in manifest.get("files", {}).items():
        path = root / name
        if not path.is_file() or hashlib.sha256(path.read_bytes()).hexdigest() != sha:
            errors.append(f"Stale/missing distribution resource: {name}")
    names = repository_files(root)
    errors += markdown_issues(root, names, data["agents"])
    map_text = (root / "skills/hard-implementation/references/systems.md").read_text(encoding="utf-8")
    for system in data["systems"]:
        for name in ("README.md", "README.ar.md"):
            if system not in (root / name).read_text(encoding="utf-8"):
                errors.append(f"{name} omits supported system: {system}")
        if f"| {system} |" not in map_text:
            errors.append(f"Native-system map omits {system}")
    return errors, names


def github_metadata(data):
    result = subprocess.run(["gh", "api", f"repos/{data['repository']}"], text=True,
                            capture_output=True, timeout=30)
    if result.returncode:
        raise ValueError("Cannot read GitHub metadata; gh authentication/network access is required")
    return json.loads(result.stdout)


def github_issues(data, actual):
    errors = []
    if actual.get("description") != data["description"]:
        errors.append("GitHub About description is stale; run scripts/sync_github_metadata.py --apply")
    if sorted(actual.get("topics", [])) != data["topics"]:
        errors.append("GitHub About topics are stale; run scripts/sync_github_metadata.py --apply")
    return errors


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--github", action="store_true", help="Also verify public GitHub description/topics, read-only")
    args = parser.parse_args()
    try:
        data = facts()
        if args.write:
            for name, text in generated_updates(ROOT, data).items():
                (ROOT / name).write_bytes(text.encode("utf-8"))
            from build_distribution import main as build_distribution
            build_distribution()
        errors, names = local_issues(ROOT, data)
        if args.github:
            errors += github_issues(data, github_metadata(data))
        for error in errors:
            print("FAIL:", error)
        if not errors:
            print(f"Consistency PASS: v{data['version']}, {len(data['agents'])} agents, "
                  f"{len(data['systems'])} systems; scanned {len(names)} repository files" +
                  ("; GitHub About verified" if args.github else ""))
        return 1 if errors else 0
    except (OSError, ValueError, KeyError, subprocess.SubprocessError) as exc:
        print("Consistency check unavailable:", exc)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
