"""Generated by scripts/build_lion_art.py; do not hand-edit."""
SOURCE_SHA256 = "99bd8ec6941c90ecaa78e1499c8b8c671e71610f33b1afc29e761574597c214e"
PALETTE = (None,
    '#f2dda3', '#eecea8', '#e5c7a8', '#f0bf88', '#eebc81', '#e7be90', '#efb87c', '#eab981',
    '#ebb479', '#e5b684', '#e4b17c', '#e5ae75', '#e5a96c', '#dcab7a', '#dda66e', '#e1a264',
    '#daa26b', '#dc9d60', '#db9558', '#d3bdaa', '#d3ac88', '#d3a071', '#d39c68', '#d19760',
    '#c9aa8f', '#afaa8b', '#cb9869', '#b79881', '#d39357', '#cc925e', '#d18e51', '#c8905e',
    '#c88d57', '#c49267', '#c28d5e', '#bf8e66', '#b28f72', '#c48867', '#c68a56', '#cb8a50',
    '#c48751', '#cf8846', '#c68448', '#be895d', '#ba8960', '#ba855d', '#be8451', '#b98354',
    '#b98056', '#b97f4e', '#bf8049', '#b87b58', '#b97b46', '#c57d3e', '#ba7b43', '#bb773b',
    '#b97339', '#b38662', '#b38257', '#b07f55', '#b27c4d', '#b37a4a', '#ad7c52', '#af7750',
    '#b07645', '#b27542', '#b0733f', '#ae7240', '#a48367', '#8a8079', '#a57854', '#907667',
    '#a6754d', '#a57248', '#a0734e', '#7f7f00', '#ab704b', '#ae6f3b', '#ad6e38', '#b56e32',
    '#ae682e', '#a56f43', '#a16f46', '#a36b3c', '#a26736', '#9c6f4a', '#9c6a41', '#946d4c',
    '#966b49', '#946947', '#906749', '#926643', '#9c673b', '#99673c', '#9a6539', '#96653d',
    '#a86228', '#a2622d', '#9e6233', '#96633d', '#986337', '#986134', '#8f6348', '#8e623e',
    '#926036', '#8e603a', '#955d39', '#9e5c26', '#8e5d35', '#8d5b34', '#9d572b', '#945732',
    '#8e572b', '#935120', '#8e4b19', '#886750', '#876043', '#885d3d', '#7b6353', '#7e5c43',
    '#85593a', '#875831', '#7f593e', '#775945', '#80543b', '#835430', '#85542e', '#88532a',
    '#83522c', '#7a5438', '#75543d', '#5e544f', '#63532c', '#804e2e', '#834e26', '#874c20',
    '#804c23', '#81481e', '#754e33', '#794b29', '#7a4824', '#744827', '#6f4e3b', '#6a4e3d',
    '#6a4937', '#6d482b', '#644b3d', '#654839', '#60493c', '#594945', '#7d4329', '#804418',
    '#b10301', '#754522', '#753f19', '#6d4528', '#6f4221', '#6c3f24', '#6c3c1e', '#6d3712',
    '#64432d', '#604332', '#623f2a', '#653d21', '#633923', '#63391b', '#643818', '#613517',
    '#623219', '#5b453d', '#5b4334', '#57433b', '#5b4133', '#574035', '#534038', '#583d2f',
    '#5b3b27', '#523d36', '#523a30', '#55382a', '#583720', '#523829', '#5b3317', '#523321',
    '#583019', '#5a2f12', '#522e16', '#542b14', '#522218', '#4d3d39', '#403f3d', '#4b3a36',
    '#4d372e', '#453733', '#4b342c', '#4d3424', '#45332c', '#3b3433', '#4c3021', '#4d2f19',
    '#472f23', '#4c2c16', '#472c1c', '#423029', '#422d23', '#3b2f2e', '#3a2c29', '#3a2b28',
    '#4d2911', '#472914', '#4a250d', '#41291b', '#402615', '#3b2922', '#342929', '#3a2519',
    '#362620', '#44220b', '#3f210e', '#352219', '#372113', '#3f1e0a', '#361e0e', '#361c0b',
    '#361704', '#2f282a', '#302320', '#2e211d', '#2f1f1a', '#281f20', '#2f1d14', '#281d1c',
    '#2d1b11', '#2e1708', '#281911', '#28160b', '#251a17', '#241710', '#1f1718', '#26140b',
    '#21140e', '#1e1410', '#1c120e', '#230f05', '#1c100b', '#1a0f0b', '#170f0e', '#170d08',
    '#150b08', '#110a07', '#110906', '#120502', '#0a0402', '#050001', '#000000',
)
IMAGES = {
    36: (
        "c-muNKnMM+8SsD!r4!e!+g#ecp<;3=Rt1x%Zdz0pUfbQ>9lmhU+G_79{g`T2O{lC)2yt}LOlwHqab!;9q6!Qpn>HL-l4~bxoTKeO"
        "d&Z>`?S(zwXey32M+Q4)<|X@^`3D9Tt+=}~Cn?m_t9b&Fl5-Qhb9>?({R=yaie@B*6!a`EnvoL_T3gnPP&1`s$MV9|P;>d5;*Lxs"
        "Y3uftMyU%DEsbqskb>m!io(o>G~=A2q%;F1E<WinYq9Vd0cNtc2uB?}-LdP^lKO^*P)BuXE?Hp~9Zzny*x~?TiO6c0l9SID%y{^F"
        "v6HiloP(#kzMOz!fh?<FLy;M;eHk<e4jjJ!YQgqueU~)NppZ#hw+7qsD9H=6=oSaa^M^wXI(p;MkJ~z$9Su&7b+$UX{qusHH0A7~"
        "BO3y=C3K;7UAwV$dzhR>U{YvRTd;kMSE!d`Qea4TL`aUXr@K2?$>E#b^;L3;+M%Jr={7d*3i6thOJu~vRFvd$%oHQbKuY!<-q1ET"
        "Ou{I{Kh(=cNkv*vj@#q^1dnnhLrpDtgLJSlhfW^Zu~pe9MBhKzQ$<WyM}d!x$>YwI7A|$i0AWrWh?+A;ZkMTt=opzM#k%V#dnqxC"
        "NV;8@V&ddBG!y2O2Kj6Kfo)e$+1nWf=_n>OBp4{?Hr13ht=%li#Kmo*&B@Le35v7BCvSIq8l)NsDug!V+A5v>zoGQ+^QG;Qd`b@5"
        "0xbNxz(Cw|aL1fVn;-{;puEoZ26vfvfBTR8`~Ny>hk>uTun@bLP6SBJq`WG7FQc^11lxky?yg@?^dH~x_2lZN%m6KIA$FzaXrNu|"
        "N_+aef<i;Wl|%B{D<^)haqTa!{X5lrL9slq1gF@-wLmq^WpjIC!h>RCV(Y?tmz;dRPt-%z<9$hQagsA92S0zzW?))xZku<aG$SN0"
        "s4hHV{?<v~CyKkuh^?8oqD#|Bf<;W<eFM<%YqwpwyRj@YHLpFhXZ~)PeQys<E04K0e|D#xgeI$4N;)u6A3A#D<<~2ds!}`i=2kWA"
        "mJxBQS+nX~&5D9dM}9><t4aOqK*4<D>xU~>x*OWtmn3vvu8|axQI%wtnctJDFQ{z2aPjJcz&vsO$+ss@U!I=S+de;G`L3NFGOjWr"
        "%pQeRsp=A88?SDeuo395^G{zq{rKhe)md|A^(>!%@9N<l<sRirVsnFRt#-V*v3b#ApqlG9U;O;}`s>Rj%a+fbyXV%!FZXUOo4>0n"
        "E~9zk{nK|2ZrTPi=feBHpI(1`cje-)`MY-AdwA>Op1z)~RSU12zH;T{*)s=^gU$K$>)oeszhB<od2z*_d$%s{+TFHw<LR$It{gcF"
        "RC5NLfUdv&_V&}SA75Txyu9M_<y{wVZ{6|o^}E-fZfrYw@Y-Q$nt$>A)3={re}1@qardn~yB|Dw`SSUl8=u}jIlOJt*`rW3kKexk"
        "^z+A$FApx>zP;<-gIDjK-@Wtp?b{1y4j()WG6w+c0s&3"
    ),
    48: (
        "c-oDWdoY{%9>$H@sy42*l5B&OuuDXn#-La=p&E(V5?;4nG>y?pN3#+|y;KdI#3fO*W{gx_;$XK+U6U54Q&KG@$BDaysM6ISMV6x4"
        "I-xyIch7dt`TqTRpWpL7-;0LEUsq19#{XS6@7}u^d!sZbHvh)|Lhs&6I-Mmbt8Ppq-fm3F%@5Vc$@#KweoaGJD#f3Y2ZH=d!GEhQ"
        "Ym6n_{4#$pC-G_?ix%N<G}tDv(3jR()|o}f&5iw%m;44kh(CJB0-!pXdKP3d`s!M^KwWCcU*q*Pwfv@*a+-s=L14P=k<1d_M0XW6"
        "ntSGl0FD2C;?dm@A`ycFfbc-7pCg&<M`gB-Kj59CQav5;kvIMvRC|4>J0+R*qklM~AS#L(RS<O|nx5UniHV6KlaFPmCT9JKzjEQR"
        "umlVSJZwFAF)=(Y9_I#7EAo!=cuYUvW4NFTf8^5=2ZSlW8G5*fDVoe=(hp%x_PK(ETo{sFaL(_Dy-mQyKek`gnMnt^42HdLL5wfM"
        "AA3M=uijqE06R+)ZUNa34YMJh{0#q9Fu+Tfbl)xt59g(vh&Y5n>Fq-sY3YTy>h0EJGs$QpsB7qFmfE_;D$|=~iv#5u4)$kZ7$ig="
        "Le|#a?|;@vOB<ERjM{HNN=*9?FA|L{^D_J2%|)7fu<gGOpxnM6io@CKVi;&$9o>^mva^8>?(~(NR<(DH&&o@Lsb<#4*!G740RMcB"
        "tPTqp>L3jrb+t@*QGSjF$haLt?L8yivJZVE*!jYgK-;5Wu!Wn8m$)47X=-8Mf%9^qF^{0lA%q<}9YZsH6MYF#TTe3ML^O>99>fNn"
        "x_IdrgUs}`NN5qeWjdm<K1iP(`!AnzxXDNhC(o##JixewFrp6y=j7yLiFI(M`g&QxQliXFgDwz1jdA^GR{~f_fZ14ElNq>#AQw9V"
        "!O+wZ)_&a^{`J>-?iiSL%n@@;Xu?PSVY?`cQ^-09v%rV@2D+VgwX?K@8bZyqtu|NVy^kXf*d5;Qi2nZMmAFs(qNcjr!bqqM0N{O@"
        "cp}mSY56S_YNDrk{B3FOM*Ch&fUUEU4l?N9?t8>_ea~Di0DqW$Al08}iNxBuVoY|a>-tRZaZMdVS0_KT?jFL&JZn07L{DW`Q66Vd"
        "IJ`YIisXYqAt{G<8ykP~&Gje7n!6!dCZ1>`18w9-|Bvbgjk0G%H#`a;nb`!UN1w!EP$?wu*ksm)g@^E6yC9GQcr-*?NAG0fNBdpf"
        "vw1`}3_yZHEj)fop}Au0#^*QP6BPW~ONDSv{e5=6Xk9HGeame_4PB3)m0t`-0TCz|3>TisU=WdB??1dpj%<GTFhR{jn7JIbu{PJy"
        "GDM!*o=rhhc{2S6w=k@k+qG+4b~@uU-246VBH_*Y`sVzBjR+#q+1ALwKnsN;T-o+t2huOO<4Kr69-Brwk-<F;&sm#jygEMc_sv^r"
        "gCx4Mqpgz><SWZmpDja=8d4)OvfTrSK(v1_(&jup19TCuW)YIAbFVIrsa%rTOlJc#Yh5iQzj|v09_7Y@RUA?n{ydgWz@~60+@b{K"
        "Z#@X_q|076HuGIdc$w#nbRb51pb6F0YW`MQ9Jh#dkwE(qV7XlbNwmV2Y}JbeIKs;d{>wrLSaQyjYOcLU$IvjSZ0mn-C4$-IEpeeV"
        "5<QH>3Zl@8W#Gs{hwgV)i0`bPWL1?ESmS&lU+qC*4wlty^*5K_)IFG%8b&*RhR&tX3M*P-FRzX!#m9T;5*CW8ic<i62h%-Tt^q-b"
        "qOJS|qLEp}Ko*T2LF1`!3Y*h^dDr#dUc7knq-?aUDwEB|!=Sd1y#Zic&fTr$>KRff-VN~c62dYVVDTM)PIJ7mF~Tc8Kk4Da5DEMI"
        "SpcSQuYVx&PFhX9nt#$WHny?&c!r+}rh}X!j(@SF)=K>W!U}F|Z1ppX3*gKkSY#}}w5DN;|3~l8%G%iIY<C@pT?kerM+haYX$UyN"
        "3SqoUGlUJY&VFm5?{lhiusTPul}~T)*phN;W>GQNRFuJLj%2qMHFqX?dtbJK!x5ablxqM6gUlNk6gT9Q=5FgxE2n3cSC$m><=moj"
        "T61xsRQ`Nm@Ik!y<<hEP$|XF}C1hfLMqFQCUApza@YJ+&ePd;AY3Y7>v5;HIl}P22%ks(oilPb${bE>fo==yodwk?xgJ^qUdWWZf"
        "f4}}}Zf$<BNupM7Zk9~WPWDTiD_M7htjJXUeZk=1eeqC7!_#ek_@C2jZ&feXR4WRpL@2Cit&~nq%3E7ovO)Ev*UimLbdGcnh($x9"
        "wvYVqtJSwEm1_O{{BxN)oXS?IT&@1Blf~~W9a&O`#~%?1Mmu_XJ{^eRSE@Coa&=>4etDur-u!caf4@*7l{S@+kGxhXUcY`>EAA4E"
        "ibXs8l<JN0_x1Iar8R|A-r6jYR<-ue$_B^h=jH}ptLElJPX+a2v1sSsPAT6ktg6;m*4`~Xmr5kEKA}uLIlHVF8y^}|^HUvNf*R3h"
        "{P46&sakovzPvF%+b5ZnKj?ohpM5>|QZX{ER4J9cqitPnJ#E|kzW@;Xjo<"
    ),
    64: (
        "c-ozpc{JPk`p4a(wa3=rN)h4OqBM?OR4ijVM=ZhUpq68a6Pb&~+DR?<h*n}7dK_Vrl3VGtH7H@i`JJ}W)|Pf6Xh@@Kt&m!-R8ovz"
        "s_jhgy>n;o@Av&Df4!dX^L{_i=l%IcPVV=g>RP$~@AGZLo!iybwKrNXzpwLurEBjr-0tpZ#rc=sXvi;WXh{37$vbyCYKvlXYgx6O"
        "ZLHd;XxfvSZ)$(Qz3=D`*@lLihK`Qb+R}t@L}gb&IljL#I-zT%rmLqc5LZ+G$13hLG&Hm_y71Uc-!svL;hrfpEFx~8wev~W1&^B6"
        "viv{dyIafB;^Q;0@d$LJr7sNZOdutP{Mg?%O2d2AwiV%ipYHhn+YUxoCCbst$^?8d3+bTannk^q#F^+CxS18%+no00@8cbvt!@32"
        "6QeY&qp_wYlAL7if}xTt=6I90$jD+EI@%*jPVPTy_~CY0QDv@II2IijiA)N!wvJ44bq#H7qzZWhR1C5>`62=q9*oQX56f`>b_~SA"
        "NZ-mE5t96Mk}C!i>Y9j2OiE6=#UG}TvoT3oNN1#HP-T7fZ+39MGsYtU-^?V!QOU_!<i^Croa`KGg)gcEg>QaRUXk6HjY$l1u4=~R"
        "R+jw+-i-^c9qD5>MW>*=9UOef)SR3gD%sl`7Ln?c)Z2#0V#*4H`lNb##isq%7|LS11nm{6s5n$I(py`{DZ4T88rBhE4+OXq$dp@-"
        "8qs8Gc4(-LrIm&IZ!B|tStpNPfsKnJ5F(S$*o4WXXBWeuwm^;3rtZNdB`^rkp4x~B3k`DuBjV%J|BY{8jW%A*ENmi05`3JKDrAOV"
        "K_Q@~Kovz*6$R5MTeGvOaAsqotCNm4*xvu&7ni~7s~~fx>WJ;d&e>#Yq&F4@hC+a<YEIS)N~&r8rWz_Iy&7dxvDVf$JbOOoUwGEY"
        "WILv1jz1-!p-JRa8}CA}1r!R@0B9wuE2wLp$C_xIP*6(9!C+(!*d-L@7yYySEcWVrPGbvKvb`?2;;rLN(AS1T^#BlnR+6H!rm@Xc"
        "XJa)5O&~D`lVhz8fXDvJ3?Hx`@D8}w$jseCUWBC%y2%?1kI1Z=n(qpB3_)5d0|?${bQCm|J;-69q1LCAtpZ~|-=dC3_t+a-LOPW>"
        "iqo>RNx5p{0E<BT#y%#|c8d%XplS*b6HO;&Ew$669NAtvsT*d*;yzPw|KT)mj3Yc~zhbN9Lqd^|HV*K@Xt1Z7pZ&-(ItAvarKP2g"
        "^ieyh6i7`BbuzY8^RJZqXIwBke<;1_VT8QaNGSGp_KhZD&p}ZB=Kg=5i1S3*I3hKz;JHH#Q!>WI+Qvu=5d69P@#*E4qc2BkQF>rY"
        "YbQ*ycX4KBRk_z$+rZMI3m1J;31OHD<e7LPMeLc-=;Wdko@NXE>T~;etG&%tqyjx7hmc4NCer&#MnPfbd5<U@+z#my?iPqZh9NN_"
        ";eG}XBdY9VYsXXv{@OstJ@#s60rqN@t&yFBr33OB5>}8N<9{|PILhAH+D7ws00?wiL(js})6Em2=S_7n2Ac%t#{QBU-H(<T8F&IE"
        "3ZidhY3b~WiL}RGa5FPAbAz5zKI5b5cli2o0LVc1gi4U9sfkV)#u{uN9Q&*N4<9p1o69NqU_&FYLnJl?iL{RmH1n{9m}!8mv;b-+"
        "{&sX&otGDo2QoVAWo7JSea0>pC-==K{C~Q8+8E7M%x|Dt7QU%*h>+|oSd6V95NKv<p{8Y`2RwP=^3PAo@?RX~DH_GXY(lNol_9~u"
        "Mrrprdy+w$9loG%<%@!Y9gvtvSg;uoXm4)|h3ToBl-JeOeavGlF9e(bX#2xlLY*{Eskr}QUk7Xa8M|jp*nHN+6BVro_C_MVj*ND<"
        "hd@ow20?(Q<>h4szSvyMlmF8RfD#by>f~artpvRADMY$iPsbS}{NWe~%olBF6^^iS%}xr63Nn=yxDtL^2LJibpn%OU<mFFl02Ec+"
        "eXP~h)zwt|3qHDk|NcEj&nUn7JTwGhgh0cMES)ipsp*0C5QseiW*&gc{X4dPZ|@6TSpiiw4Kr^iZDnO;CDWqZPXdO9hK2J5=MiuS"
        "0)19b-^wv5JF74l3O5a$=v_VV^cDuE)wWh$(miofO$q4hYpkiPpa#(JD9Zn+e`I88zAY-k0}_PwFx1xrJA_oEUX3^h2j(B{AHGw>"
        "9Z3&Xt0SqG<WK5pn4b%^ktKlw0BGy~Ap#z-M*0V6xfu}<cvgg|iJl1@MIa|vB%HTB-SG3_&#Nk{N3x$Ijt$384{Gjp&cfKz_>=-b"
        "%Pj5q1ax<^I(upO@^p9mi_uUEBTp>0m`orLGB21LO#duA=r=q#kRBc$)oHvN00##<`dI2{YHKTKoHO)4z6O4H(B0XKFE5PtK!n4g"
        "7FcRa2_BV9Ag9C_fJAR+59)DiTT>f{M;>1uWd;>GI=k9fYAdUsQi+YS{cr-i?{}7FW)^3-!z18!6{O6#Xo#<G79}ek<iGQFn3Y!B"
        "&ui^DeCH-<gSI3mx*A(Mx@amZtE9E%e^vBheJj&5iraJDBjWA;n(B#)H?(lf$}G8BYJOvLukJ5t`L%a1r>*XaB&M-V+1c5~>e@z@"
        "YKp2+ot?GE2HvkNO)I3+)8Sb6NVGko+|2|*YD&OTnu8}-R$lm-U%Gtxl3&{4Q4Nqpr8Z`}XsRg#w3SrdOFKG_+yA~Am)q1%OplL&"
        "7kk18cxXxsK0Kj>@?*xv%EI1ddB1=FKhUM46~8EYV|LQlF4{`!3IH{LNm1>cWBoN{I6SGUsyWv`1r3WM1_l+Dd&Hwl==_YAE6?}*"
        "l>9*EAcLC6i~dAvW0-Xa=8UqEqKclrUew(W-*XMs1;l3BXn$-}VR$qa9TY*x@W-a$xqKXL<@Ewg-Q3UoFK(yvMCpT6D%C*?6{fDF"
        "r~rXMZ0qmUzsI{P>)LvUr-pH*8PV8_*l=vig@Tk4CS{<=|KZ+BT3SFr07xCUuw2e$7H9ocTOWBwSy90q9vg^b9UIVbmoYRZSexv+"
        "aRH4^O-UgW60pUTrWSsg?9^_qY%W~?Tb>tVVTjU5q9^-W0l>~`swy7X;8NV}d&f5)>k<2nP`Dwe%Oz%{L|<!4!M8MJV%s^Fb#()-"
        "U;myp{dnQo%AGn+MQUaf!VUm%)>hT<Xvr;VZ8#3Uhfl{>*9H4h#!y{dMtpH2`brbMDhNyIs|M-H>w^69F6Ujk{@AaQTS5pyq3i%^"
        "j`|w5QM9`1j(gq5;W<9D%99-Ode-~v3JR|g&@Cl><z56jr$4|zSJ%KCWbS8R0MadD60sDRr-POn3}RSR`CV;y_xtwcp33-X@%|Qj"
        "W_zrw4S%(`iHK)rL^lm`M{C}LAdtB%x&LHPNFru7g`3!E0nYn>*+1G}*1@`aJin*U#+M~;L^I36wW<EPDpCuUG?)<A&SWwN^1c9p"
        "{QP9R{0Too3Kma98Nu}o({OE5lVjgjcYgS9^6c64n>U+FOKZDpF9p55BvN@hGw2GJ(!!kW{5Bv!w!8+iHi}3n*;o(|Pd(eZv9&Sw"
        "$oJJZ+CIL2MkIQVi?_srwW;zJ61^&(K1gVqo#PAG?6Iyq*#=bpNDNOvqv7sBrZM~t;VPTa(cRkmA^)B)yq;MWOQe#m^>xWu^UW%H"
        "OF5H5;LdShz1rQKof~eeYq>Re6HyqCb}x-}8{toG2wt!nSUsQk=QB&2(*6CN^;PNC<Zv^6kWOqT(z(nz880is9c(AjZgCRIBMNZ+"
        "UzM#1dnX0F>FX>;=STjh#n(Ightj20v1I$@7;To>PHCcW+XrR%D=v4I&LQHz>!X#Ym)0@Hx&&i_CqwM%>4*16?tSE+&Ab*%-|Z}l"
        "#oKQrV|)&i&TQc_+h^y5ujaT+4t)S!{@p-xdFcjEARHchF~VcBA54$47;?Y#FM2E87p+To_V&es`Oygqr;mA)IXC-?JIA4O259)Y"
        ";oi!jHOaPkwZC(j!D27nW3xv-@e2!!ulM%$MLU~2hx=0D2A@xv<51{a&fF|>c5q;Hlvp(+XnP@9e<Kzz_p~mLbh2i~S>xlsT)@ws"
        "zutT+7KwKDrH30E;<ZtZkV)^G9ehP+ayj#yURwXg<ho>aRlL5l#J)Q@-Z?To&0_uf_4Cuh(&pQ@q8+JJy1%wB5l+m_F*$v+94=*I"
        "V1AxIDG=<gieK>7x7S5)rh7(Mx5p>hpUnI4EQ+K%BI(}VyY1}*iG)8t!5J8wo$c%6&kE<~x7J@SuL^j)ot>TK^>Nk+tNsCN`ce1i"
        "{KCpxnfjf7ypxJ02fO^;0nP+}ZuaIJe{O#M&Gr^=SvGLd&hp;!%ulkksDH#_KYH*v|9o*>B>IO~=HG@yvLzG_aQVWyKBlaB;hJcR"
        "x4y<(5{cd}?kqiBobI0Pc=m|#QUCt}KOa#Y"
    ),
}
